markdown:         rdiscount
pygments:         true
paginate:         8

title:            quxiaofeng.me
url:              http://www4.comp.polyu.edu.hk/~csxfqu
feed:             http://www4.comp.polyu.edu.hk/~csxfqu/atom.xml
author:
  name :          Qu Xiaofeng
  email :         csxfqu@comp.polyu.edu.hk
description:      "csxfqu - quxiaofeng's official site"


about: 			  "I am Qu Xiaofeng. A Ph.D. candidate in Hong Kong Polytechnic University. I'm interested in Biometrics, Pattern Recognition, Machine Vision, Computer Vision, Image Processing, and Embedded System. I want to make beautiful practical convenient high-performance real-world applications."
follow:
    github:       https://github.com/quxiaofeng
    twitter:      http://www.twitter.com/quxiaofeng
    facebook:     http://www.facebook.com/quxiaofeng
    linkedin:     http://hk.linkedin.com/pub/xiaofeng-qu/20/57b/b17
    google:       https://plus.google.com/u/0/118103723037880699787/posts
    mendeley:     http://www.mendeley.com/profiles/xiaofeng-qu/
    weibo:        http://weibo.com/quxiaofeng
    tencent:      http://t.qq.com/quxiaofeng
    gscholar:     http://scholar.google.com.hk/citations?user=zgRM4foAAAAJ&hl=en

style: 			  http://www4.comp.polyu.edu.hk/~csxfqu/css/style.css
blogName: 		  QuXiaoFeng.me
blogDesc: 		  Qu Xiaofeng's official site
blogInfo:                 This site records my life and work in PolyU. It helps me make my life easier, and my thoughts organized. Hope it can help somebody else.

comments :
  provider : disqus
  disqus :
    short_name : csxfqu
